### ISSUE TITLE
De-duplicate `MediaFile.assets`

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/chowda#117]
# Duplicates
They aren't all duplicates, and the first one isn't always the media.

https://chowda.wgbh-mla.org/admin/media-file/detail/cpb-aacip-00d35d49377

![Image](https://github.com/WGBH-MLA/chowda/assets/2718445/7fa2a063-103b-4f42-b718-89a28764fb27)

This media file has 12 assets:
- cpb-aacip-00d35d49377.mxf.sha256 x2
- cpb-aacip-00d35d49377.mp4 (video) x3
- cpb-aacip-00d35d49377.mxf.mediainfo.xml x2
- cpb-aacip-00d35d49377.mp4.mediainfo.xml
- cpb-aacip-00d35d49377.mxf x2
- cpb-aacip-00d35d49377_proxy.mp4.mp4
- cpb-aacip-00d35d49377.mp4.sha256

```[tasklist]
### Tasks
- [ ] `IngestFlow`: `kind=video`
- [ ] `IngestFlow`: error on multiple media files
- [ ] https://github.com/WGBH-MLA/mario/pull/16
```

**Comment by mrharpo** [comment]
Found another error guid: [cpb-aacip-15-pr7mp4vv7s](https://chowda.wgbh-mla.org/admin/media-file/detail/cpb-aacip-15-pr7mp4vv7s)

In this case, there are 2 assets with the same filename, but the first does not have a `type`, which causes a pipeline error in the start step.

Exposed via first large batch run: The error happened before the db could get updated with the record, so the run never makes it into the database.

https://mario.wgbh-mla.org/Pipeline/argo-pipeline-qh8rk/start/t-5e1667d4?direction=asc&group=true&order=startTime&section&status=failed

**Comment by mrharpo** [comment]
[cpb-aacip-ffc3907d6c3](https://chowda.wgbh-mla.org/admin/media-file/detail/cpb-aacip-ffc3907d6c3) - 8 assets

**Comment by singlesoliloquy** [comment]
Use sony ci ID to make it invalid
