### ISSUE TITLE
🌶 PEP 621

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/chowda#14]
# PEP 621
TLDR: poetry came before the [python standard for metadata in pyproject.toml](https://peps.python.org/pep-0621/), so they do things in a (now) non-standard way. 

This will allow us to make use of python's `[project.optional-dependencies]`, so we can install "extra" dependencies with pip, and not need an extra package manager for normal (non-developer) images.

e.g: 
```shell
pip install chowda[test]
```

## Todo

```[tasklist]
### PEP 621
- [x] Migrate `pyproject.toml` from poetry to PDM
- [x] Update docker build stages
- [x] Update pytest action for new install process
- [ ] Update docs action for new install process
- [ ] Publish to pypi
```
