### ISSUE TITLE
Source MMIF

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/chowda#151]
As a Clammer, I can select the `source_mmif` to be used for a Media File in a Batch.

Before starting a Batch, I can choose to:
- Use the existing `source_mmif` if, available (default)
- Use a "blank" MMIF
  - ("new", "empty", "clean"?)
- Select a `source_mmif` for a MediaFile from a list of available MMIF
- Select from a list of available MMIF from a specific Pipeline

Optionally, there can be other selection methods:
- `n`th Most recent
- `n`th Oldest
- Matching string query

```[tasklist]
### Tasks
- [x] Add `MMIF` table
- [x] Update `MediaFile` model with `source_mmif`, `mmifs`
- [ ] https://github.com/WGBH-MLA/chowda/issues/165
- [ ] https://github.com/WGBH-MLA/chowda/pull/168
- [ ] https://github.com/WGBH-MLA/chowda/issues/174
- [x] Add `input_mmifs` to `Batch`
- [ ] https://github.com/WGBH-MLA/chowda/issues/166
- [ ] Select `source_mmif` from `Pipeline`
```

**Comment by mrharpo** [comment]
Unblocked because workaround found!

Add hidden form element with value. https://github.com/andrew-d/python-multipart/issues/38#issuecomment-1747732447
