### ISSUE TITLE
Setup API token authentication

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/chowda#153]
Setup authentication for ~~eventual~~ existing API routes
```[tasklist]
### Tasks
- [x] Create Chowda API
- [x] Create Chowda API permissions
- [x] Create Mario app (Machine to Machine)
- [x] Assign Chowda API permissions to Mario
- [x] Create Chowda JWT validation function
- [x] Add JWT validation dependency to API routes
- [ ] Check `permissions` for authorization
- [x] Add tests
- [ ] https://github.com/WGBH-MLA/mario/issues/18
```
