### ISSUE TITLE
Allow "blank" MMIF Source as an option for Batches

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/chowda#165]
### Summary

As a Clammer
When I am creating a Batch
And when the "MMIF Source" field is left blank
And when the Batch is started
Then the Batch will run it's associated Media Files through it's associated Pipeline using "blank" MMIF as input
In order to get Pipeline results without an input MMIF.

```[tasklist]
### Tasks
- [x] Add "new MMIF" checkbox
- [x] Parse form in Chowda
- [x] Update logic in Pipeline
```
