### ISSUE TITLE
Add MMIFs to batch

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/chowda#176]
As a clammer, I can select many MMIFs and:

```[tasklist]
### Tasks
- [x] Add MMIFs to a new batch
- [x] Add MMIFs to an existing batch
- [ ] 🦟 Raise better error if multiple selected MMIF refer to same MMIF file
```
