### ISSUE TITLE
Add `duration` to SonyCiAsset

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/chowda#178]
```[tasklist]
### Tasks
- [ ] Add `duration` to model
- [ ] Create migration
- [ ] Perform migration
- [ ] Update view fields
- [ ] Update Ingest to include `duration`
- [ ] Re-ingest
```
