### ISSUE TITLE
Create batch via GUID list from txt file

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/chowda#56]
**Done when**
Chowda Batch can be created from a list of GUIDs from uploading a text file
```[tasklist]
### Tasks
- [x] Overrwite Batch `validate`
- [x] Change `media_files` to text area
- [x] Return validation errors to user
- [ ] Add tests
```
