### ISSUE TITLE
Pydantic 2.0

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/chowda#75]
# Pydantic 2
Pydantic 2.0 was released last week.

## Migration
https://docs.pydantic.dev/latest/migration/

A code transformation tool is available:
```shell
pip install bump-pydantic
```

```[tasklist]
### Tasks
- [x] Read Migration guide
- [x] Use `bump-pydantic` tool (if necessary)
- [x] Update models (if necessary)
- [x] Pin pydantic version to `~2.0`
- [x] ~~Run alembic migrations~~
```

**Comment by mrharpo** [comment]
SonyCi `0.2.0` is updated to use `pydantic 2.1.1`, 🎊 

However, SQLModel has yet to be updated, although, it appears to be not far off:

https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6387149
> Yep, SQLModel will be updated next. 🚀
> ~ tiangolo

**Comment by singlesoliloquy** [comment]
If it ends up not being easy, then postpone.
