### ISSUE TITLE
Add database migrations to deployment

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/chowda#76]
```[tasklist]
### Tasks
- [ ] https://github.com/WGBH-MLA/chowda/issues/58
- [ ] https://github.com/WGBH-MLA/chowda/pull/77
- [x] Run migrations in production
- [ ] https://github.com/WGBH-MLA/chowda/issues/108
```

**Comment by mrharpo** [comment]
# k8s migrations
After some research, a fully automated k8s migration process seems more complicated than we initially anticipated:

## Strategy
### On deploy:
- (optional) Backup database
- Scale down Chowda to 0 pods
- Perform migrations
### On success:
- Update Chowda deployment image
- Scale back up to `n` pods
### On failure:
- Rollback db
- Scale back up to `n` pods

## Problems
This simplistic strategy has some drawbacks:
- Downtime for Chowda (not a big problem)
- Can't be run as init container in Chowda deployment, because there could be multiple instances that try to run

## Options
- `bash` script
  - Using `kubectl`
  - Run migrations manually, when needed
- `Metaflow`
  - Running in argo, attached to argo-events
  - Needs special permissions to change kube deployments
- `argo-cd`
  - Attach to [resource_hooks](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/): `Sync` or `PreSync`

**Comment by mrharpo** [comment]
Closing and punting to #108 🏈
